cookie="SID=SDAAAFaBARSOBBE8kWUrUFHQfYv_OY8_J2-ziol8_DYw5fQGGDS3DFSDFSRR-cP4cdrkv2FeAxsrDFSRasd5gerfsfeSdcP0qMeBMZi2oDhx92xCMGQ-tIyWscbc2SfFGLOHC54CH2yqq8_vaPv0f6diPBIQemZ-BWmK8xbA0cNQKuoreRv06VmIGAWERAEdFAfaDAEFd; HSID=AdcaPdsfstDFSB-; SSID=AabASFSGDasdtlC2VJvs_er;"
url="https://translate.google.com/translate_a/sg?client=t&cm=g&hl=en&xt=MLkJrhsCDFSDASFVvqQDNZTMaSDAGRSFADfgrfawdo2FjzG3hJJt"
